### ISSUE TITLE
UPS Naming Issue

### ISSUE THREAD

**Issue by picard001** [reneboer/vera-UPSSensor#1]
Line 132 in I_UPSSensor1.xml currently reads this:

var, val = ret:match('VAR ups ([%w%.]+) "(.+)"') 

"ups" is hard coded and should be set to the variable upsName

var, val = ret:match('VAR '.. upsName ..' ([%w%.]+) "(.+)"')

With NUT one can name the UPS anything they'd like, so this code only works if the name of the UPS is "ups"

**Comment by reneboer** [comment]
Hi,

Thanks for finding this. I updated to V2.1 with this issue fixed.
